# Generated by Django 4.2.3 on 2023-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerShip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='hardwareType',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subcategory',
            new_name='SubType',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='itemName',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='categoryName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='keyword',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
