# Generated by Django 4.2.3 on 2023-07-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerShip', '0002_rename_name_category_hardwaretype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='SerShip/static/images/'),
        ),
    ]
